SalesWebsite/Controllers/ShoppingCartController.cs
using SalesWebsite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SalesWebsite.Controllers
{
    public class ShoppingCartController : Controller
    {
        MyUpdateBusinessEntities allDAO = new MyUpdateBusinessEntities();

        [ChildActionOnly]
        public ActionResult ShoppingCartPartial()
        {
            ViewBag.SumOfAmount = GetSumOfAmount() != 0 ? GetSumOfAmount() : 0;
            ViewBag.SumOfAllBills = GetSumOfAmount() == 0 ? 0 : GetSumOfAllBills();
            return PartialView();
        }


        // create session

        public List<ShoppingCartItem> GetShoppingCart()
        {
            List<ShoppingCartItem> shoppingCartItems = Session["shoppingCartItemsByTrieuDD"] as List<ShoppingCartItem>;
            if (shoppingCartItems == null)
            {
                shoppingCartItems = new List<ShoppingCartItem>();
                Session["shoppingCartItemsByTrieuDD"] = shoppingCartItems;
            }
            return shoppingCartItems;
        }
        public ActionResult WatchShoppingCart()
        {
            List<ShoppingCartItem> shoppingCartItems = GetShoppingCart();
            return View(shoppingCartItems);
        }
        // for display in cart by session
        public int GetSumOfAmount()
        {
            List<ShoppingCartItem> shoppingCartItems = Session["shoppingCartItemsByTrieuDD"] as List<ShoppingCartItem>;
            if (shoppingCartItems == null)
            {
                return 0;
            }
            return shoppingCartItems.Sum(trieudd => trieudd.Amount);
        }
        public decimal GetSumOfAllBills()
        {
            List<ShoppingCartItem> shoppingCartItems = Session["shoppingCartItemsByTrieuDD"] as List<ShoppingCartItem>;
            if (shoppingCartItems == null)
            {
                return 0;
            }
            return shoppingCartItems.Sum(trieudd => trieudd.Bill);
        }
        public ActionResult AddShoppingCart(int id, string url)
        {
            // check in db
            Product product = allDAO.Products.SingleOrDefault(trieudd => trieudd.id == id);
            if (product == null)
            {
                Response.StatusCode = 400;
                return null;
            }

            // check in shopping cart
            List<ShoppingCartItem> shoppingCartItems = GetShoppingCart();
            ShoppingCartItem shoppingCartItem = shoppingCartItems.SingleOrDefault(trieudd => trieudd.ProductID == id);


            if (shoppingCartItem == null)
            {
                shoppingCartItem = new ShoppingCartItem(id);
                if (product.inventory < shoppingCartItem.Amount)
                {
                    return View("Notification");
                }
                else
                {
                    shoppingCartItems.Add(shoppingCartItem);
                }
            }
            else
            {
                if (product.inventory < shoppingCartItem.Amount + 1)
                {
                    return View("Notification");
                }
                else
                {
                    shoppingCartItem.Amount++;
                    shoppingCartItem.Bill = shoppingCartItem.Amount * shoppingCartItem.Price;
                }
            }
            return Redirect(url);
        }
        public ActionResult AddShoppingCartAjax(int id)
        {
            // check in db
            Product product = allDAO.Products.SingleOrDefault(trieudd => trieudd.id == id);
            if (product == null)
            {
                Response.StatusCode = 400;
                return null;
            }

            // check in shopping cart
            List<ShoppingCartItem> shoppingCartItems = GetShoppingCart();
            ShoppingCartItem shoppingCartItem = shoppingCartItems.SingleOrDefault(trieudd => trieudd.ProductID == id);


            if (shoppingCartItem == null)
            {
                shoppingCartItem = new ShoppingCartItem(id);
                if (product.inventory < shoppingCartItem.Amount)
                {
                    return Content("<script>alert('This product sold all !!!');window.location.reload();</script>");
                }
                else
                {
                    shoppingCartItems.Add(shoppingCartItem);
                }
            }
            else
            {
                if (product.inventory < shoppingCartItem.Amount + 1)
                {
                    return Content("<script>alert('This product sold all !!!');window.location.reload();</script>");
                }
                else
                {
                    shoppingCartItem.Amount++;
                    shoppingCartItem.Bill = shoppingCartItem.Amount * shoppingCartItem.Price;
                }
            }
            ViewBag.SumOfAmount = GetSumOfAmount();
            ViewBag.SumOfAllBills = GetSumOfAllBills();
            return PartialView("ShoppingCartPartial");
        }






        // update shopping cart item
        [HttpGet]
        public ActionResult UpdateShoppingCart(int id)
        {
            if (Session["shoppingCartItemsByTrieuDD"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            // check exist?? in db
            Product product = allDAO.Products.SingleOrDefault(trieudd => trieudd.id == id);
            if (product == null)
            {
                Response.StatusCode = 400;
                return null;
            }

            // check exist in session
            List<ShoppingCartItem> shoppingCartItems = GetShoppingCart();
            ShoppingCartItem shoppingCartItem = shoppingCartItems.SingleOrDefault(trieudd => trieudd.ProductID == id);
            if (shoppingCartItem == null)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.ShoppingCartItems = shoppingCartItems;

            return View(shoppingCartItem);
        }
        [HttpPost]
        public ActionResult UpdateShoppingCart(ShoppingCartItem shoppingCartItem)
        {
            Product product = allDAO.Products.SingleOrDefault(trieudd => trieudd.id == shoppingCartItem.ProductID);
            if (product.inventory < shoppingCartItem.Amount)
            {
                return View("Notification");
            }


            List<ShoppingCartItem> shoppingCartItems = GetShoppingCart();
            ShoppingCartItem newShoppingCartItem = shoppingCartItems.Find(trieudd => trieudd.ProductID == shoppingCartItem.ProductID);
            newShoppingCartItem.Amount = shoppingCartItem.Amount;
            newShoppingCartItem.Bill = newShoppingCartItem.Price * newShoppingCartItem.Amount;

            return RedirectToAction("WatchShoppingCart");
        }


        // delete shopping cart item
        public ActionResult DeleteShoppingCart(int id)
        {
            if (Session["shoppingCartItemsByTrieuDD"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            Product product = allDAO.Products.SingleOrDefault(trieudd => trieudd.id == id);
            if (product == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            List<ShoppingCartItem> shoppingCartItems = GetShoppingCart();
            ShoppingCartItem shoppingCartItem = shoppingCartItems.SingleOrDefault(trieudd => trieudd.ProductID == id);
            if (shoppingCartItem == null)
            {
                return RedirectToAction("Index", "Home");
            }
            shoppingCartItems.Remove(shoppingCartItem);

            return RedirectToAction("WatchShoppingCart");
        }



        // order shopping cart item
        public ActionResult Order(Customer customer_parameter)
        {
            if (Session["shoppingCartItemsByTrieuDD"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            Customer customer = new Customer();
            if (Session["ssByTrieuDD"] == null)
            {
                // khach van lai
                customer = customer_parameter;
            }
            else
            {
                // khach co tai khoan
                Member member = Session["ssByTrieuDD"] as Member;
                customer.member_id = member.id;

                //   Member member = allDAO.Members.Where(trieudd => trieudd.id == customer.member_id).First();

                customer.name = member.fullname;
                customer.address = member.address;
                customer.email = member.email;
                customer.phone = member.phone;
            }
            allDAO.Customers.Add(customer);
            allDAO.SaveChanges();

            // order
            Order order = new Order();
            order.customer_id = customer.id;
            order.date = DateTime.Now;
            order.delivery_status = false;
            order.is_paid = false;
            order.incentives = 0;
            order.is_cancel = false;
            order.is_delete = false;
            allDAO.Orders.Add(order);
            allDAO.SaveChanges();

            //order detail
            List<ShoppingCartItem> shoppingCartItems = GetShoppingCart();
            foreach (var shoppingCartItem in shoppingCartItems)
            {
                DetailOrder detailOrder = new DetailOrder();
                detailOrder.order_id = order.id;
                detailOrder.product_id = shoppingCartItem.ProductID;
                detailOrder.product_name = shoppingCartItem.ProductName;
                detailOrder.amount = shoppingCartItem.Amount;
                detailOrder.product_price = shoppingCartItem.Price;
                allDAO.DetailOrders.Add(detailOrder);
            }
            allDAO.SaveChanges();

            Session["shoppingCartItemsByTrieuDD"] = null;

SalesWebsite/Views/ShoppingCart/Notification.cshtml
<h1> This product is sold all !!!</h1>

SalesWebsite/Views/ShoppingCart/ShoppingCartPartial.cshtml
<div id="divShoppingCart" class="cart box_1">
    <a href="@Url.Action("WatchShoppingCart", "ShoppingCart")">
        <h3>
            <div class="total">
                @ViewBag.SumOfAllBills.ToString("#,##") VNĐ
                (@ViewBag.SumOfAmount items)
            </div>
            <img src="~/Content/images/cart.png" alt="">
        </h3>
    </a>
    <p><a href="@Url.Action("WatchShoppingCart","ShoppingCart")" class="simpleCart_empty">See detail</a></p>

</div>

SalesWebsite/Views/ShoppingCart/UpdateShoppingCart.cshtml
@using SalesWebsite.Models
@model ShoppingCartItem


@{
    ViewBag.Title = "UpdateShoppingCart";
    Layout = "~/Views/Layout/DetailProductLayout.cshtml";
}


@{
    List<ShoppingCartItem> products = ViewBag.ShoppingCartItems;
}


<style>
    table, td, th {
        border: 1px solid;
        border-color: chocolate;
        border-collapse: collapse;
    }
</style>
<div class="col-md-9">
    <table width="100%">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Image</th>
            <th>Amount</th>
            <th>Price</th>
            <th>Bill</th>
            <th colspan="2">ACTION</th>
        </tr>

        @foreach (var product in products)
        {
            // product(model) with id updated in products(viewbag)
            if (Model.ProductID == product.ProductID)
            {
                using (Html.BeginForm("UpdateShoppingCart", "ShoppingCart"))
                {
                    <tr>
                        <th>@product.ProductID @Html.Hidden("ProductID", product.ProductID) </th>
                        <th>@product.ProductName</th>
                        <th><img src="@Url.Content("~/Content/imagesProducts/"+product.Image)" height="150" width="150" /></th>

                        <th>
                            @Html.TextBox("Amount", product.Amount, new { @class = "classTxtAmount" })
                            <p id="txtAmountError"></p>
                        </th>

                        <th>@product.Price.ToString("#,##")</th>
                        <th>@product.Bill.ToString("#,##")</th>
                        <th>   <input type="submit" id="btnUpdate" value="Update now !!!" />  </th>
                        <th>@Html.ActionLink("delete this product from cart ...", "DeleteShoppingCart", new { @id = product.ProductID })</th>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <th>@product.ProductID</th>
                    <th>@product.ProductName</th>
                    <th><img src="@Url.Content("~/Content/imagesProducts/"+product.Image)" height="150" width="150" /></th>
                    <th>@product.Amount  </th>
                    <th>@product.Price.ToString("#,##")</th>
                    <th>@product.Bill.ToString("#,##")</th>
                    <th colspan="2">@Html.ActionLink("delete this product from cart ...", "DeleteShoppingCart", new { @id = product.ProductID })</th>
                </tr>
            }

        }

    </table>

</div>

<script>
    $('#btnUpdate').click(function () {
        var amount = $('.classTxtAmount').val();
        if (isNaN(amount) || amount <= 0) {
            $('#txtAmountError').text('Số lượng phải là số nguyên lớn hơn 0 đồng chí ơi 400 Bad request');
            return false;
        }
    });
</script>

SalesWebsite/Views/ShoppingCart/WatchShoppingCart.cshtml
@using SalesWebsite.Models
@model IEnumerable<ShoppingCartItem>
@{
    ViewBag.Title = "WatchShoppingCart";
    Layout = "~/Views/Layout/DetailProductLayout.cshtml";
}

@if (Model.Count() == 0)
{
    <h1>
        Empty shopping cart ^^
    </h1>
    <a href="/Home/Index" class="btn btn-success">Shopping now</a>
    return;
}
<style>
    table, td, th {
        border: 1px solid;
        border-color: chocolate;
        border-collapse: collapse;
    }
</style>
<div class="col-md-9">
    <table width="100%">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Image</th>
            <th>Amount</th>
            <th>Price</th>
            <th>Bill</th>
            <th colspan="2">ACTION</th>
        </tr>

        @foreach (var product in Model)
        {
            <tr>
                <th>@product.ProductID</th>
                <th>@product.ProductName</th>
                <th><img src="@Url.Content("~/Content/imagesProducts/"+product.Image)" height="150" width="150" /></th>
                <th>@product.Amount </th>
                <th>@product.Price.ToString("#,##")</th>
                <th>@product.Bill.ToString("#,##")</th>
                <th>@Html.ActionLink("update amount here ...", "UpdateShoppingCart", new { @id = product.ProductID })</th>
                <th>@Html.ActionLink("delete this product from cart ...", "DeleteShoppingCart", new { @id = product.ProductID })</th>
            </tr>
        }
    </table>



    @using (Html.BeginForm("Order", "ShoppingCart"))
    {
        if (Session["ssByTrieuDD"] == null)
        {
            <div id="divCustomerInfomation">
                <table align="center" class="table">
                    <tr>
                        <td align="center" colspan="2"><b>Customer Information !!!</b></td>
                    </tr>
                    <tr>
                        <td>Fullname:</td>
                        <td>
                            @Html.TextBox("name")
                            <p id="msgName" style="color:red"></p>
                        </td>

                    </tr>
                    <tr>
                        <td>Address:</td>
                        <td>
                            @Html.TextBox("address")
                            <p id="msgAddress" style="color:red"></p>
                        </td>
                    </tr>
                    <tr>
                        <td>Email:</td>
                        <td>
                            @Html.TextBox("email")
                            <p id="msgEmail" style="color:red"></p>
                        </td>
                    </tr>
                    <tr>
                        <td>Phone:</td>
                        <td>
                            @Html.TextBox("phone")
                            <p id="msgPhone" style="color:red"></p>
                        </td>
                    </tr>
                </table>
            </div>

        }



        <br />
        <br />


        <div class="divOrder" style="text-align:right">

            <input type="submit" value="Order" id="btnOrder" class="btn btn-danger" />
            <a class="btn btn-success" href="/Home/Index">Buy anymore</a>

            @if (Session["ssByTrieuDD"] == null)
            {
                <script>
                    $('#btnOrder').click(function () {
                        var isError = 0;
                        if ($('#name').val() == '') {
                            $('#msgName').text('Bạn không được bỏ trống tên mình');
                            isError++;
                        } else {
                            $('#msgName').text('');
                        }

                        if ($('#address').val() == '') {
                            $('#msgAddress').text('Bạn không được bỏ trống địa chỉ của mình');
                            isError++;
                        } else {
                            $('#msgAddress').text('');
                        }

                        if ($('#phone').val() == '') {
                            $('#msgPhone').text('Bạn không được bỏ trống số điện thoại của mình');
                            isError++;
                        } else {
                            $('#msgPhone').text('');
                        }



                        if ($('#email').val() == '') {
                            $('#msgEmail').text('Bạn không được bỏ trống email của mình');
                            isError++;
                        } else if (!/^[0-9A-Za-z]+[0-9A-Za-z]*@@[\w\d.]+\.\w{2,4}$/.test($('#email').val())) {
                            $('#msgEmail').text('Không đúng định dạng mail rồi bạn ơi, thì ra đây là một trò đùa !!!');
                            isError++;
                        } else {
                            $('#msgEmail').text('');
                        }


                        if (isError != 0) {
                            // prohibit submit to server
                            return false;
                        }
                    });
                </script>
            }

        </div>
    }
</div>

<style>
    input[type="submit"] {
        padding: 15px;
        margin: 0;
    }
</style>