SalesWebsite/Controllers/AdminController.cs
using SalesWebsite.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SalesWebsite.Controllers
{
    public class AdminController : Controller
    {
        MyUpdateBusinessEntities allDAO = new MyUpdateBusinessEntities();
        public ActionResult Index()
        {
            return View(allDAO.Products.Where(trieudd => trieudd.is_delete == false));
        }

        [HttpGet]
        public ActionResult AddNew()
        {
            ViewBag.Providers = new SelectList(allDAO.Providers.OrderBy(trieudd => trieudd.name), "id", "name");
            ViewBag.ProductTypes = new SelectList(allDAO.ProductTypes.OrderBy(trieudd => trieudd.id), "id", "name");
            ViewBag.Producers = new SelectList(allDAO.Producers.OrderBy(trieudd => trieudd.name), "id", "name");
            return View(new Product());
        }
        [HttpGet]
        public ActionResult AddNew1()
        {
            ViewBag.Providers = new SelectList(allDAO.Providers.OrderBy(trieudd => trieudd.name), "id", "name");
            ViewBag.ProductTypes = new SelectList(allDAO.ProductTypes.OrderBy(trieudd => trieudd.id), "id", "name");
            ViewBag.Producers = new SelectList(allDAO.Producers.OrderBy(trieudd => trieudd.name), "id", "name");
            return View(new Product());
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult AddNew1(Product product, HttpPostedFileBase[] uploadFile)
        {
            // load again combobox
            ViewBag.Providers = new SelectList(allDAO.Providers.OrderBy(trieudd => trieudd.name), "id", "name");
            ViewBag.ProductTypes = new SelectList(allDAO.ProductTypes.OrderBy(trieudd => trieudd.id), "id", "name");
            ViewBag.Producers = new SelectList(allDAO.Producers.OrderBy(trieudd => trieudd.name), "id", "name");

            // check image is exist
            if (uploadFile[0].ContentLength > 0)
            {
                var path = Path.Combine(Server.MapPath("~/Content/imagesProducts"), Path.GetFileName(uploadFile[0].FileName));

                if (System.IO.File.Exists(path))
                {
                    ViewBag.Msg = "This image is exist";
                    return View(new Product() { name = "TrieuDZ" });
                }
                else
                {
                    uploadFile[0].SaveAs(path);
                    product.image = uploadFile[0].FileName;
                }
            }
            allDAO.Products.Add(product);
            allDAO.SaveChanges();
            return RedirectToAction("Index");

        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult AddNew(Product product, HttpPostedFileBase[] uploadFile)
        {
            // load again combobox
            ViewBag.Providers = new SelectList(allDAO.Providers.OrderBy(trieudd => trieudd.name), "id", "name");
            ViewBag.ProductTypes = new SelectList(allDAO.ProductTypes.OrderBy(trieudd => trieudd.id), "id", "name");
            ViewBag.Producers = new SelectList(allDAO.Producers.OrderBy(trieudd => trieudd.name), "id", "name");

            // check image is exist
            if (uploadFile[0].ContentLength > 0)
            {
                var path = Path.Combine(Server.MapPath("~/Content/imagesProducts"), Path.GetFileName(uploadFile[0].FileName));

                if (System.IO.File.Exists(path))
                {
                    ViewBag.Msg = "This image is exist";
                    return View(new Product() { name = "TrieuDZ" });
                }
                else
                {
                    uploadFile[0].SaveAs(path);
                    product.image = uploadFile[0].FileName;
                }
            }
            allDAO.Products.Add(product);
            allDAO.SaveChanges();
            return RedirectToAction("Index");

        }

        [HttpGet]
        public ActionResult UpdateProduct(int? id)
        {
            //no pass value of parameter -- không truyền id
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            //
            Product product = allDAO.Products.SingleOrDefault(trieudd => trieudd.id == id);
            if (product == null)
            {
                return HttpNotFound();
            }




            // load again combobox
            ViewBag.Providers = new SelectList(allDAO.Providers.OrderBy(trieudd => trieudd.name), "id", "name", product.provider_id);
            ViewBag.ProductTypes = new SelectList(allDAO.ProductTypes.OrderBy(trieudd => trieudd.id), "id", "name", product.product_type_id);
            ViewBag.Producers = new SelectList(allDAO.Producers.OrderBy(trieudd => trieudd.name), "id", "name", product.producer_id);

            return View(product);
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult UpdateProduct(Product product)
        {
            //// load again combobox
            //ViewBag.Providers = new SelectList(allDAO.Providers.OrderBy(trieudd => trieudd.name), "id", "name", product.provider_id);
            //ViewBag.ProductTypes = new SelectList(allDAO.ProductTypes.OrderBy(trieudd => trieudd.id), "id", "name", product.product_type_id);
            //ViewBag.Producers = new SelectList(allDAO.Producers.OrderBy(trieudd => trieudd.name), "id", "name", product.producer_id);


            //if (ModelState.IsValid)
            //{
                allDAO.Entry(product).State = System.Data.Entity.EntityState.Modified;
            allDAO.SaveChanges();
            return RedirectToAction("Index");
            //}


            // load again combobox
            ViewBag.Providers = new SelectList(allDAO.Providers.OrderBy(trieudd => trieudd.name), "id", "name");
            ViewBag.ProductTypes = new SelectList(allDAO.ProductTypes.OrderBy(trieudd => trieudd.id), "id", "name");
            ViewBag.Producers = new SelectList(allDAO.Producers.OrderBy(trieudd => trieudd.name), "id", "name");
            return View(product);
        }
    }
}

SalesWebsite/Views/Admin/AddNew.cshtml
@model SalesWebsite.Models.Product

@{
    ViewBag.Title = "AddNew";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css" />
<script>
    $(function () {
        $('#datePicker').datepicker();
    });
</script>


<script src="https://cdn.tiny.cloud/1/5v94pfmijg6ejp4ruonntc1x5rcinjc4mbtjemxg6f6bg53e/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: 'textarea',
        plugins: 'a11ychecker advcode casechange formatpainter linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tinycomments tinymcespellchecker',
        toolbar: 'a11ycheck addcomment showcomments casechange checklist code formatpainter pageembed permanentpen table',
        toolbar_mode: 'floating',
        tinycomments_mode: 'embedded',
        tinycomments_author: 'Author name',
    });
</script>

<h2>Add New By TrieuDD</h2>

@using (Html.BeginForm("AddNew", "Admin", FormMethod.Post, htmlAttributes: new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price_updated_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" id="datePicker" class="form-control" name="price_updated_date" readonly />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.configuration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.configuration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.configuration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.description, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.inventory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.inventory, new { htmlAttributes = new { @class = "form-control", @min = 0 } })
                @Html.ValidationMessageFor(model => model.inventory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.view, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.view, new { htmlAttributes = new { @class = "form-control", @min = 0 } })
                @Html.ValidationMessageFor(model => model.view, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vote, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vote, new { htmlAttributes = new { @class = "form-control", @min = 0 } })
                @Html.ValidationMessageFor(model => model.vote, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.comment, new { htmlAttributes = new { @class = "form-control", @min = 0 } })
                @Html.ValidationMessageFor(model => model.comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sold, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sold, new { htmlAttributes = new { @class = "form-control", @min = 0 } })
                @Html.ValidationMessageFor(model => model.sold, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.is_new, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.is_new)
                    @Html.ValidationMessageFor(model => model.is_new, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.provider_id, "provider_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Providers", null, htmlAttributes: new { @class = "form-control" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.producer_id, "producer_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Producers", null, new { @class = "form-control" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.product_type_id, "product_type_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductTypes", null, htmlAttributes: new { @class = "form-control" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.is_delete, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.is_delete)
                    @Html.ValidationMessageFor(model => model.is_delete, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <input type="file" name="uploadFile" class="form-control" />
                <span style="color:red">@ViewBag.Msg</span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="uploadFile" class="form-control" />
                <span style="color:red">@ViewBag.Msg</span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="uploadFile" class="form-control" />
                <span style="color:red">@ViewBag.Msg</span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="uploadFile" class="form-control" />
                <span style="color:red">@ViewBag.Msg</span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="uploadFile" class="form-control" />
                <span style="color:red">@ViewBag.Msg</span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SalesWebsite/Views/Admin/Index.cshtml
@model IEnumerable<SalesWebsite.Models.Product>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
    WebGrid webGrid = new WebGrid(source: Model, rowsPerPage: 5);
}

@webGrid.GetHtml(
    tableStyle: "divTable",
    headerStyle: "divHeader",
    footerStyle: "divFooter",
    rowStyle: "divRow",
    alternatingRowStyle: "divAlternatingRow",
    columns: webGrid.Columns
    (
        webGrid.Column("id", "Mã sản phẩm"),
        webGrid.Column("name", "Tên sản phẩm"),
        webGrid.Column("description", "Miêu tả sản phẩm", format: trieudd => @Html.Raw(trieudd.description)),
        webGrid.Column("image", "Hình ảnh sản phẩm", format: trieudd => Html.Raw("<img src = \"../../Content/imagesProducts/" + trieudd.image + "\" >")),
        webGrid.Column(format: trieudd => Html.ActionLink("Update...", "UpdateProduct", new { @id = trieudd.id })),
        webGrid.Column(format: trieudd => Html.ActionLink("Delete...", "DeleteProduct", new { @id = trieudd.id }))
    )
)

<style>
    .divTable {
        width: 100%;
    }

    .divTable, th, td {
        border: 1px solid chocolate;
        border-collapse: collapse;
    }

    .divHeader {
        background-color: black;
    }

        .divHeader th a {
            color: white;
        }

    .divFooter {
        font-weight: bold;
    }

    .divAlternatingRow {
        background-color: blueviolet;
        color: white;
    }

    .divRow {
        background-color: antiquewhite;
        color: black;
    }
</style>

SalesWebsite/Views/Admin/UpdateProduct.cshtml
@model SalesWebsite.Models.Product
@{
    ViewBag.Title = "UpdateProduct";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css" />
<script>
    $(function () {
        $('#datePicker').datepicker();
    });
</script>


<script src="https://cdn.tiny.cloud/1/5v94pfmijg6ejp4ruonntc1x5rcinjc4mbtjemxg6f6bg53e/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

<script>
    tinymce.init({
        selector: 'textarea',
        plugins: 'a11ychecker advcode casechange formatpainter linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tinycomments tinymcespellchecker',
        toolbar: 'a11ycheck addcomment showcomments casechange checklist code formatpainter pageembed permanentpen table',
        toolbar_mode: 'floating',
        tinycomments_mode: 'embedded',
        tinycomments_author: 'Author name',
    });
</script>

<h2>Add New By TrieuDD</h2>

@using (Html.BeginForm("UpdateProduct", "Admin", FormMethod.Post, htmlAttributes: new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price_updated_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("price_updated_date", Model.price_updated_date.Value.ToString("dd/MM/yyyy"), new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.configuration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea name="configuration">@Model.configuration</textarea>
                @Html.ValidationMessageFor(model => model.configuration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextArea("description", @Model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.inventory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.inventory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.inventory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.view, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.view, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.view, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vote, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vote, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vote, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sold, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sold, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sold, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.is_new, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.is_new)
                    @Html.ValidationMessageFor(model => model.is_new, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.provider_id, "provider_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Providers", null, htmlAttributes: new { @class = "form-control" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.producer_id, "producer_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Producers", null, new { @class = "form-control" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.product_type_id, "product_type_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductTypes", null, htmlAttributes: new { @class = "form-control" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.is_delete, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.is_delete)
                    @Html.ValidationMessageFor(model => model.is_delete, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <input type="file" name="image" value="@Model.image" class="form-control" />
                <span style="color:red">@ViewBag.Msg</span>
                <br />
                <img src="@Url.Content("~/Content/imagesProducts/"+Model.image)" height="150" width="150" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <input type="file" name="image1" class="form-control" />
                <span style="color:red">@ViewBag.Msg</span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <input type="file" name="uploadFile" class="form-control" />
                <span style="color:red">@ViewBag.Msg</span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <input type="file" name="uploadFile" class="form-control" />
                <span style="color:red">@ViewBag.Msg</span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <input type="file" name="uploadFile" class="form-control" />
                <span style="color:red">@ViewBag.Msg</span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>