SalesWebsite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CaptchaMvc.HtmlHelpers;
using SalesWebsite.Models;

namespace SalesWebsite.Controllers
{
    public class HomeController : Controller
    {

        MyUpdateBusinessEntities allDAO = new MyUpdateBusinessEntities();

        public ActionResult Index()
        {
            // listPhone: phone, isNew, !isDelete
            var listPhone = allDAO.Products.Where(trieudd =>
                trieudd.product_type_id == 1
                &&
                trieudd.is_new == true
                &&
                trieudd.is_delete == false
                );
            ViewBag.ListPhone = listPhone;

            // listLaptop: laptop, isNew, !isDelete
            var listLaptop = allDAO.Products.Where(trieudd =>
                 trieudd.product_type_id == 3
                 &&
                 trieudd.is_new == true
                 &&
                 trieudd.is_delete == false
                 );
            ViewBag.ListLaptop = listLaptop;

            // listTablet: tablet, isNew, !isDelete
            var listTablet = allDAO.Products.Where(trieudd =>
                trieudd.product_type_id == 2
                &&
                trieudd.is_new == true
                &&
                trieudd.is_delete == false
                );
            ViewBag.ListTablet = listTablet;

            return View();
        }


        [ChildActionOnly]
        public ActionResult MenuPartial()
        {
            return PartialView(allDAO.Products);
        }


        [HttpGet]
        public ActionResult Register()
        {
            ViewBag.question = new SelectList(LoadSecretQuestions());
            Member member = new Member();
            return View(member);
        }
        [HttpGet]
        public ActionResult RegisterByMS()
        {
            return View(new Member());
        }

        [HttpPost]
        public ActionResult Register(Member member,FormCollection formCollection)
        {
            ViewBag.question = new SelectList(LoadSecretQuestions());
            if (this.IsCaptchaValid("Lỗi rồi bạn ơi !!!"))
            {
                if (ModelState.IsValid)
                {
                    allDAO.Members.Add(member);
                    allDAO.SaveChanges();
                    ViewBag.Msg = "OK, đăng ký thành công";
                }
                else
                {
                    ViewBag.Msg = "Bad register request";
                }
                return View(new Member());
            }
            ViewBag.Msg = "Captcha sai rồi bạn ơi";
            return View(new Member());
        }
        public List<string> LoadSecretQuestions()
        {
            return new List<string>()
            {
                "What is your pet's name ??",
                "Where are your parents meet up first time ??",
                "TrieuDD is the most handsome boy over the world ??"
            };
        }

        public ActionResult Login(FormCollection formCollection)
        {

            string user = formCollection.Get("txtUser");
            string pass = formCollection["txtPass"];
            var member = allDAO.Members.SingleOrDefault(trieudd => trieudd.account.Equals(user) && trieudd.password.Equals(pass));
            if (member != null)
            {
                Session["ssByTrieuDD"] = member;
                return Content("<script>window.location.reload()</script>");
            }
            return Content("Your account or password wrong !!!");
        }

        public ActionResult Logout()
        {
            Session["ssByTrieuDD"] = null;
            return RedirectToAction("Index");
        }
    }
}

SalesWebsite/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SalesWebsite.Models;
using PagedList;
namespace SalesWebsite.Controllers
{
    public class ProductController : Controller
    {
        MyUpdateBusinessEntities allDAO = new MyUpdateBusinessEntities();

        // display style 1
        [ChildActionOnly]
        public ActionResult ProductStyle1Parital()
        {
            return PartialView();
        }

        // display style 2
        [ChildActionOnly]
        public ActionResult ProudctStyle2Partial()
        {
            return PartialView();
        }

        //see detail of product by id passed into
        public ActionResult DetailProduct(int? idd)
        {
            if (idd == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //find product by id and !isDelete ------> return product^null
            var product = allDAO.Products.SingleOrDefault(trieudd => trieudd.id == idd && trieudd.is_delete == false);
            if (product == null)
                return HttpNotFound();
            return View(product);
        }

        public ActionResult ProductsByTypeAndProvider(int? typeId, int? producerId, int? page)
        {

            if (typeId == null || producerId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var products = allDAO.Products.Where(trieudd => trieudd.product_type_id == typeId && trieudd.producer_id == producerId);
            if (products.Count() == 0)
            {
                return HttpNotFound();
            }

            // pagination
            if (Request.HttpMethod != "GET")
            {
                page = 1;
            }
            int pageSize = 6;
            int pageNumber = (page ?? 1);

            ViewBag.TypeID = typeId;
            ViewBag.ProducerID = producerId;
            return View(products.OrderBy(trieudd => trieudd.id).ToPagedList(pageNumber, pageSize));
        }
    }
}

SalesWebsite/Views/Home/Index.cshtml
@using SalesWebsite.Models;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}
@{
    IEnumerable<Product> listPhone = ViewBag.ListPhone as IEnumerable<Product>;
    IEnumerable<Product> listLaptop = (IEnumerable<Product>)ViewBag.ListLaptop;
    IEnumerable<Product> listTablet = ViewBag.ListTablet;
}

<div class="container">
    <div class="content-top">
        @Html.Partial("~/Views/Product/ProductStyle1Parital.cshtml", listTablet)
 
        @Html.Partial("~/Views/Product/ProductStyle1Parital.cshtml", listPhone)
    </div>

    <div class="content-top-bottom">
        @Html.Partial("~/Views/Product/ProudctStyle2Partial.cshtml", listLaptop)
    </div>

</div>

SalesWebsite/Views/Home/MenuPartial.cshtml
@using SalesWebsite.Models;
@model IEnumerable<Product>

<div class=" h_menu4">
    <ul class="memenu skyblue">
        <li class="showhide" style="display: none;"><span class="title">MENU</span><span class="icon1"></span><span class="icon2"></span></li>
        <li class="active grid" style="display: inline;"><a class="color8" href="@Url.Action("Index","Home")">Home</a></li>

        @foreach (var groupItem in Model.GroupBy(trieudd => trieudd.ProductType))
        {
            if (groupItem.Key != null)
            {
                <li style="display: inline;">
                    <a class="color1" href="#">@groupItem.Key.name </a>
                    <div class="mepanel">
                        <div class="row">
                            <div class="col1">
                                <div class="h_nav">
                                    <ul>
                                        @foreach (var groupItem1 in groupItem.GroupBy(trieudd => trieudd.Producer))
                                        {
                                            if (groupItem1.Key != null)
                                            {
                                                <li><a href="@Url.Action("ProductsByTypeAndProvider","Product",new {  @typeId = groupItem.Key.id, @producerId = groupItem1.Key.id })">@groupItem1.Key.name</a></li>
                                            }
                                        }
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            }
        }
        @*<li style="display: inline;">
                <a class="color1" href="#">Men</a>
                <div class="mepanel">
                    <div class="row">
                        <div class="col1">
                            <div class="h_nav">
                                <ul>
                                    <li><a href="products.html">Accessories</a></li>
                                    <li><a href="products.html">Bags</a></li>
                                    <li><a href="products.html">Caps &amp; Hats</a></li>
                                    <li><a href="products.html">Hoodies &amp; Sweatshirts</a></li>
                                    <li><a href="products.html">Jackets &amp; Coats</a></li>
                                    <li><a href="products.html">Jeans</a></li>
                                    <li><a href="products.html">Jewellery</a></li>
                                    <li><a href="products.html">Jumpers &amp; Cardigans</a></li>
                                    <li><a href="products.html">Leather Jackets</a></li>
                                    <li><a href="products.html">Long Sleeve T-Shirts</a></li>
                                    <li><a href="products.html">Loungewear</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col1">
                            <div class="h_nav">
                                <ul>
                                    <li><a href="products.html">Shirts</a></li>
                                    <li><a href="products.html">Shoes, Boots &amp; Trainers</a></li>
                                    <li><a href="products.html">Shorts</a></li>
                                    <li><a href="products.html">Suits &amp; Blazers</a></li>
                                    <li><a href="products.html">Sunglasses</a></li>
                                    <li><a href="products.html">Sweatpants</a></li>
                                    <li><a href="products.html">Swimwear</a></li>
                                    <li><a href="products.html">Trousers &amp; Chinos</a></li>
                                    <li><a href="products.html">T-Shirts</a></li>
                                    <li><a href="products.html">Underwear &amp; Socks</a></li>
                                    <li><a href="products.html">Vests</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col1">
                            <div class="h_nav">
                                <h4>Popular Brands</h4>
                                <ul>
                                    <li><a href="products.html">Levis</a></li>
                                    <li><a href="products.html">Persol</a></li>
                                    <li><a href="products.html">Nike</a></li>
                                    <li><a href="products.html">Edwin</a></li>
                                    <li><a href="products.html">New Balance</a></li>
                                    <li><a href="products.html">Jack &amp; Jones</a></li>
                                    <li><a href="products.html">Paul Smith</a></li>
                                    <li><a href="products.html">Ray-Ban</a></li>
                                    <li><a href="products.html">Wood Wood</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </li>*@



        <li class="grid" style="display: inline;">
            <a class="color2" href="#">	Brands</a>
            <div class="mepanel">
                <div class="row">
                    @foreach (var groupItem in Model.GroupBy(trieudd => trieudd.ProductType))
                    {
                        <div class="col1">
                            @if (groupItem.Key != null)
                            {
                                <div class="h_nav">
                                    <ul>

                                        <h1>@groupItem.Key.name</h1>

                                        @foreach (var groupItem1 in groupItem.GroupBy(trieudd => trieudd.Producer))
                                        {
                                            if (groupItem1.Key != null)
                                            {
                                                <li><a href="@Url.Action("ProductsByTypeAndProvider", "Product", new { @typeId = groupItem.Key.id, @producerId = groupItem1.Key.id })">@groupItem1.Key.name</a></li>
                                            }


                                        }
                                    </ul>

                                </div>
                            }
                        </div>
                    }
                </div>
            </div>
        </li>
        <li style="display: inline;"><a class="color4" href="blog.html">About us</a></li>
        <li style="display: inline;"><a class="color6" href="contact.html">Conact</a></li>
    </ul>
</div>

SalesWebsite/Views/Home/Register.cshtml
@using CaptchaMvc.HtmlHelpers
@using CaptchaMvc
@using SalesWebsite.Models
@model Member

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Layout/DetailProductLayout.cshtml";
}



<div class=" register">
    <h1>Regist to join our universe</h1>
    @using (Ajax.BeginForm("Register", "Home", new AjaxOptions()
    {
        InsertionMode = InsertionMode.InsertBefore,
        UpdateTargetId = "txtOutput",
    }))
    {
        @Html.AntiForgeryToken()
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="col-md-5 register-top-grid">


            <h3>Personal infomation</h3>
            <div>
                @Html.LabelFor(model => model.fullname)
                @Html.ValidationMessageFor(Model => Model.fullname)
                @Html.TextBoxFor(Model => Model.fullname)
            </div>
            <div>
                @Html.LabelFor(model => model.address)
                @Html.ValidationMessageFor(Model => Model.address)
                @Html.TextBoxFor(Model => Model.address)
            </div>
            <div>
                @Html.LabelFor(model => model.email)
                @Html.ValidationMessageFor(Model => Model.email)
                @Html.TextBoxFor(Model => Model.email)
            </div>
            <div>
                @Html.LabelFor(model => model.phone)
                @Html.ValidationMessageFor(Model => Model.phone)
                @Html.TextBoxFor(Model => Model.phone)
            </div>
        </div>

        <div class="col-md-4 register-bottom-grid register-top-grid">
            <h3>Login information</h3>
            <div>
                @Html.LabelFor(model => model.account)
                @Html.ValidationMessageFor(Model => Model.account)
                @Html.TextBoxFor(Model => Model.account)
            </div>
            <div>
                @Html.LabelFor(model => model.password)
                @Html.ValidationMessageFor(Model => Model.password)
                @Html.PasswordFor(Model => Model.password, new { @id = "password", @placeholder = "Enter your password !!!" })
                @*<input id="password" name="txtPassword" type="password" placeholder="Enter your password !!!" required="" />*@
            </div>
            <div>
                @Html.LabelFor(model => model.password)
                <label id="txtPasswordConfirm"></label>
                <input id="password_confirm" type="password" placeholder="Confirm Password" oninput="checkRePass(this)" />
                <script type="text/javascript">
                    function checkRePass(input) {
                        if (input.value != document.getElementById('password').value) {
                            input.setCustomValidity('Password Must be Matching.')
                        } else {
                            input.setCustomValidity('')
                        }
                    }
                </script>
            </div>

            <div>
                @Html.LabelFor(model => model.question)
                @Html.DropDownList("question")
            </div>
            <div>
                @Html.LabelFor(model => model.answear)
                @Html.ValidationMessageFor(model => model.answear)
                @Html.TextBoxFor(Model => Model.answear)
            </div>

            @Html.MathCaptcha()
            <a class="news-letter" href="#">
                <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i> </i>Sign Up for Newsletter</label>
            </a>
            <br />
            <div style="color:chocolate" id="txtOutput">@ViewBag.Msg</div>
            <br />
            <input type="submit" value="submit">
        </div>


        <div class="clearfix"> </div>
    }
</div>

SalesWebsite/Views/Home/RegisterByMS.cshtml
@model SalesWebsite.Models.Member

@{
    ViewBag.Title = "RegisterByMS";
    Layout = "~/Views/Layout/DetailProductLayout.cshtml";
}

<h2>RegisterByMS</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Member</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.account, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.account, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.account, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fullname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fullname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fullname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.question, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.question, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.answear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.answear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.answear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.member_type_id, "member_type_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("member_type_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.member_type_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>