SalesWebsite/Controllers/SearchController.cs
using SalesWebsite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;

namespace SalesWebsite.Controllers
{
    public class SearchController : Controller
    {
        MyUpdateBusinessEntities allDAO = new MyUpdateBusinessEntities();

        [HttpGet]
        public ActionResult SearchResult(string key, int? page)
        {
            if (Request.HttpMethod != "GET")
            {
                page = 1;
            }
            int pageNumber = (page ?? 1);
            int pageSize = 6;
            var products = allDAO.Products.Where(trieudd => trieudd.name.Contains(key));
            ViewBag.Key = key;
            return View(products.OrderBy(trieudd => trieudd.name).ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public ActionResult SearchResult(string key)
        {
            ////if (Request.HttpMethod != "GET")
            ////{
            ////    page = 1;
            ////}
            ////int pageNumber = (page ?? 1);
            ////int pageSize = 6;
            ////var products = allDAO.Products.Where(trieudd => trieudd.name.Contains(key));
            ////ViewBag.Key = key;
            //return View(products.OrderBy(trieudd => trieudd.name).ToPagedList(pageNumber, pageSize));

            // muc dich de co tu khoa tren url va ngan gon code
            return RedirectToAction("SearchResult", new { @key = key });
        }


        public ActionResult SearchResultPartial(string key)
        {
            var products = allDAO.Products.Where(trieudd => trieudd.name.Contains(key));
            ViewBag.Key = key;
            return PartialView(products.OrderBy(trieudd => trieudd.price));
        }
    }
}

SalesWebsite/Views/Layout/HeaderTopPartial.cshtml
@using SalesWebsite.Models
@model Member

<div class="header-top">
    <div class="container">
        <div class="search">
            @using (Html.BeginForm("SearchResult", "Search"))
            {
                <input type="text" name="key" placeholder="Nhập tên sản phẩm" value="Search " onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
                <input type="submit" value="Search now !!!">
            }
        </div>
        <div class="header-left">
            <ul>
                @if (Session["ssByTrieuDD"] != null && Session["ssByTrieuDD"].ToString() != "")
                {
                    Member member = (Member)Session["ssByTrieuDD"];
                    <li>Chào bạn @member.fullname</li>
                    <br />
                    @Html.ActionLink("Đăng xuất nhưng mãi bên nhau bạn nhé !!!", "Logout", "Home");
                }
                else
                {
                    <li style="display:inline;"><a href="#" id="btnLogin">Login</a></li>
                    <li style="display:inline;"><a href="@Url.Action("Register","Home")">Register</a></li>
                }
                <li></li>
            </ul>
            @Html.Action("ShoppingCartPartial", "ShoppingCart")
            <div class="clearfix"> </div>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>


<style>
    #popup_login {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0,0,0,.7);
        z-index: 1999;
        display: none;
    }
</style>


<div id="Content">



    <div id="popup_login">

        <!-- begin div login-->
        @*<link href="~/Content/css/style_loginForm.css" rel="stylesheet" />
        *@
        <style>
            .main {
                margin: 7em auto 0;
                width: 30%;
            }

            .user {
                text-align: right;
                vertical-align: unset;
                margin-right: 5.2em;
            }

            .login {
                padding: 2em 0;
            }

            .inset {
                position: relative;
                background: #fff;
                padding: 2em 2em;
                border-radius: 0.3em;
                -webkit-border-radius: 0.3em;
                -o-border-radius: 0.3em;
                -moz-border-radius: 0.3em;
            }

                .inset:before {
                    content: '';
                    width: 0;
                    height: 0;
                    border: 20px solid #FFF;
                    border-top: 0 solid rgba(0, 0, 0, 0) !important;
                    border-right: 13px solid rgba(0, 0, 0, 0) !important;
                    border-left: 13px solid rgba(0, 0, 0, 0);
                    left: 77.1%;
                    top: -5.3%;
                    position: absolute;
                }

            form span {
                display: block;
                font-size: 1em;
                color: #787878;
                padding-bottom: 5px;
                font-weight: 600;
                font-family: 'Open Sans', sans-serif;
            }

            #popup_login input[type="text"], input[type="Password"] {
                padding: 9px;
                width: 90%;
                font-size: 1.1em;
                margin: 18px 0px;
                border: 2px solid#EAEEF1;
                color: #666666;
                background: #EAEEF1;
                font-family: 'Open Sans', sans-serif;
                font-weight: 600;
                margin-left: 5px;
                outline: none;
                -webkit-transition: all 0.3s ease-out;
                -moz-transition: all 0.3s ease-out;
                -ms-transition: all 0.3s ease-out;
                -o-transition: all 0.3s ease-out;
                transition: all 0.3s ease-out;
            }

                #popup_login input[type="text"]:hover, input[type="Password"]:hover, #active {
                    background: #fff;
                    border: 2px solid #609EC3;
                    outline: none;
                }

            .sign {
                padding: 10px 0;
            }

            .forget-pass {
                float: right;
            }

            .submit {
                padding: 2px 2px;
                float: left;
                margin-right: 11px;
            }

                .submit input[type="submit"] {
                    background: #F06B37;
                    border: none;
                    outline: none;
                    padding: 0.55em 1.3em 0.6em;
                    cursor: pointer;
                    font-family: 'Open Sans', sans-serif;
                    color: #FFF;
                    font-size: 0.9em;
                    border-radius: 1.3em;
                    -webkit-border-radius: 1.3em;
                    -moz-border-radius: 1.3em;
                    -o-border-radius: 1.3em;
                    transition: 0.5s all;
                    -webkit-transition: 0.5s all;
                    -moz-transition: 0.5s all;
                    -o-transition: 0.5s all;
                    font-weight: 600;
                }

                    .submit input[type="submit"]:hover {
                        background: #62A0C4;
                    }

            .forget {
                float: right;
            }

            .forget-pass a {
                float: right;
                color: #898888;
                font-size: 0.95em;
                margin-top: 13px;
                transition: 0.5s all;
                -webkit-transition: 0.5s all;
                -moz-transition: 0.5s all;
                -o-transition: 0.5s all;
                font-weight: 600;
                font-family: 'Open Sans', sans-serif;
            }

                .forget-pass a:hover {
                    text-decoration: underline;
                }
        </style>

        <div class="main">
            <div class="user">
                <img src="~/Content/images/user.jpg" alt="" id="imageExit">
                <script type="text/javascript">
                    //$('#imageExit').click(function () {
                    //    $('.txtTaikhoan').val() = '';
                    //    $('.txtPassword').val() = '';
                    //    hideLogin();
                    //});

                    // popup login
                    $("#btnLogin").click(function () {
                        //$("#popup_login").css({
                        //    "display": "block",
                        //    "background-color": "red",
                        //});
                        // $("#popup_login").show(2000);
                        $("#popup_login").fadeIn(1500);
                        //   $("#popup_login").slideDown(4000);
                    });

                    // hide login
                    function hideLogin() {
                        // $("#popup_login").css("display", "none");
                        //  $("#popup_login").slideUp(2000);
                        //   $("#popup_login").hide(2000);
                        $("#popup_login").fadeOut(500);
                        $('.txtTaikhoan').val('');
                        $('.txtPassword').val('');
                        $('#txtErrorMsg').text('made by trieudd');
                    }
                    $("#imageExit").click(hideLogin);

                    // get account and password
                    $("#btnLogin1").click(function () {
                        var acc = $(".txtTaikhoan").val();
                        var pass = $(".txtPassword").val();

                        if (acc == "" || pass == "") {
                            alert("không được bỏ trống 1 cái gì cả !!!");
                            return;
                        }

                        alert("Tài khoản của bạn là [" + acc + "], có mật khẩu là: [" + pass + "]");
                    });
                </script>
            </div>
            <div class="login">
                <div class="inset">
                    <!-----start-main---->
                    @using (Ajax.BeginForm("Login", "Home",
                        new AjaxOptions()
                        {
                            InsertionMode = InsertionMode.Replace,
                            UpdateTargetId = "txtErrorMsg"
                        }))
                    {
                        <div>
                            <span><label>Username</label></span>
                            <span><input type="text" name="txtUser" value="" class="textbox txtTaikhoan" id="active" required=""></span>
                        </div>
                        <div>
                            <span><label>Password</label></span>
                            <span><input type="password" name="txtPass" class="password txtPassword" required=""></span>
                        </div>
                        <h1 style="font:bold; text-align:left; color:red" id="txtErrorMsg">made by trieudd</h1>
                        <div class="sign">
                            <div class="submit">
                                <input type="submit" onclick="" value="LOGIN" id="btnLogin1">
                            </div>
                            <span class="forget-pass">
                                <a href="#">Forgot Password?</a>
                            </span>
                            <div class="clear"> </div>
                        </div>
                    }
                </div>
            </div>
            <!-----//end-main---->
        </div>

        <!-- end div login-->
    </div>

</div>